### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by rrydbirk** [perslab/CELLEX#25]
First time running CELLEX, I get the following error.

>>> data.shape
(28621, 118345)
>>> metadata.shape
(118345, 1)

I disabled ANOVA gene filtering (see https://github.com/perslab/CELLEX/issues/24).
Any advice?

eso.compute(verbose=True)
Computing DET ...
    esw ...
    empirical p-values ...
    esw_s ...
    finished in 0 min 49 sec
Computing EP ...
    esw ...
    empirical p-values ...
    esw_s ...
    finished in 0 min 0 sec
Computing GES ...
    esw ...
    empirical p-values ...
    esw_s ...
    finished in 0 min 47 sec
Computing NSI ...
    esw ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rasmusr/bin/anaconda3/lib/python3.7/site-packages/cellex/esobject.py", line 120, in compute
    esm_result = getattr(metrics, m.lower())(self.summary_data, verbose, compute_meta)
  File "/home/rasmusr/bin/anaconda3/lib/python3.7/site-packages/cellex/metrics/nsi.py", line 123, in nsi
    esw = _nsi(df, verbose)
  File "/home/rasmusr/bin/anaconda3/lib/python3.7/site-packages/cellex/metrics/nsi.py", line 69, in _nsi
    fc_mean = fc_ranked_norm.mean(axis=1)
  File "/home/rasmusr/bin/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 138, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "/home/rasmusr/bin/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 57, in _count_reduce_items
    items *= arr.shape[ax]
IndexError: tuple index out of range

**Comment by rrydbirk** [comment]
This was solved here: https://github.com/perslab/CELLEX/issues/24. Thanks for the help!
